import { db } from './client.js';
import { initSchema } from './schema.js';

export const categoriesData = [
  {
    id: 'personalized-gifts',
    name: 'Personalized Gifts',
    icon: '🎁',
    description: 'Thoughtful custom gifts crafted with love, precision, and heartfelt personal touches.',
    display_order: 1,
    image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'pens-stationery',
    name: 'Pens & Stationery',
    icon: '✒️',
    description: 'Precision-engraved luxury metal, zari, and wooden pens for professionals and connoisseurs.',
    display_order: 2,
    image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'keychains',
    name: 'Keychains',
    icon: '🔑',
    description: 'Custom name-engraved metal, LED, wooden, and acrylic keychains built to last.',
    display_order: 3,
    image_url: 'https://images.unsplash.com/photo-1614312015093-6c7b9c6f2c7d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'leather-gifts',
    name: 'Leather Gifts',
    icon: '💼',
    description: 'Bespoke faux & premium leather wallets, passport sleeves, sunglass cases, and hampers.',
    display_order: 4,
    image_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'stainless-steel',
    name: 'Stainless Steel & Kada',
    icon: '✨',
    description: 'Sleek stainless steel kadas, 4-sided secret pendant bars, and custom charm jewellery.',
    display_order: 5,
    image_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'bottles-mugs',
    name: 'Bottles & Mugs',
    icon: '☕',
    description: 'Smart LED temperature bottles, hot/cold vacuum flask gift sets, and custom ceramic mugs.',
    display_order: 6,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'diaries',
    name: 'Diaries & Organizers',
    icon: '📔',
    description: 'Executive leather planner diaries with 4-year calendar and matching luxury pen gift sets.',
    display_order: 7,
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'gift-sets',
    name: 'Gift Sets & Combos',
    icon: '✨',
    description: 'Curated 2-in-1, 3-in-1, and 4-in-1 bespoke gift combos packaged in luxury boxes.',
    display_order: 8,
    image_url: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'apparel',
    name: 'Custom Apparel',
    icon: '👕',
    description: 'Premium heavyweight cotton hoodies, 200 GSM oversized tees, and custom dryfit collared shirts.',
    display_order: 9,
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'home-lifestyle',
    name: 'Home & Lifestyle',
    icon: '🏠',
    description: 'Plush velvet fur cushions, high-precision gaming mouse pads, and vibrant fridge magnets.',
    display_order: 10,
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
  },
];

export const productsData = [
  // 1. 2D Metal Covers
  {
    id: '2d-metal-phone-cover',
    name: '2D Metal Phone Cover (Custom Print)',
    category_id: 'personalized-gifts',
    price: 250,
    mrp: 399,
    description: 'Glossy high-definition metal back plate phone case with reinforced shock-absorbing bumper. Available for over 250+ iPhone, Samsung, OnePlus, Vivo, Oppo, Realme, and Xiaomi models.',
    customisation_options: JSON.stringify(['Any Photo / Custom Design', 'Name / Monogram Print']),
    variants: JSON.stringify(['250+ Phone Models Supported', 'Glossy Finish', 'Matte Metal Finish']),
    packaging: 'Protective Retail Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },

  // 2. Pens & Keychains
  {
    id: 'multi-led-pen',
    name: 'Multi LED Glowing Name Pen',
    category_id: 'pens-stationery',
    price: 200,
    mrp: 299,
    description: 'Striking LED light pen with custom laser-engraved name that lights up upon click. Comes standard in a gift paper box packing.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Red Light', 'Blue Light', 'White Light', 'Green Light']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Premium Clear Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'keychain-multi-led',
    name: 'Multi LED Illuminated Keychain',
    category_id: 'keychains',
    price: 250,
    mrp: 350,
    description: 'Futuristic glowing acrylic/metal keychain with illuminated name engraving. A stunning accessory for bike and car keys.',
    customisation_options: JSON.stringify(['With Name Engraving', 'Logo / Crown Symbol']),
    variants: JSON.stringify(['Multicolor RGB Cycle', 'Single Blue', 'Single Red']),
    packaging: 'Standard Protective Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1614312015093-6c7b9c6f2c7d?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'led-pen-led-keychain-set',
    name: 'LED Pen + LED Keychain Luxury Set',
    category_id: 'gift-sets',
    price: 350,
    mrp: 499,
    description: 'Matching illuminated pair: Custom engraved LED Pen and LED Keychain nested in a velvety black presentation box.',
    customisation_options: JSON.stringify(['Name Engraving on Both Items']),
    variants: JSON.stringify(['Black Theme', 'Blue Theme']),
    packaging: 'Deluxe Velvet Foam Gift Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'gold-zari-pen',
    name: 'GOLD Zari Royal Metal Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 399,
    description: 'Regal golden filigree zari pattern metal ballpoint pen with precision micro-engraving for your signature touch.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Gold / Black Accent', 'Full Gold Zari']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Premium Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'gold-zari-pen-keychain-set',
    name: 'GOLD Zari Pen + Keychain Set',
    category_id: 'gift-sets',
    price: 299,
    mrp: 450,
    description: 'A stately duo featuring the Gold Zari Pen and matching gold-embossed keychain presented in an elegant gift box.',
    customisation_options: JSON.stringify(['With Name Engraving on Pen & Keychain']),
    variants: JSON.stringify(['Imperial Gold Finish']),
    packaging: 'Premium Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'matt-pen',
    name: 'Executive MATT Finish Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 350,
    description: 'Sleek satin matte black body with polished gold clip and trims. Smooth German ink refill with laser name etching.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Matte Black / Gold Trim', 'Matte Navy']),
    packaging: 'With Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Case', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'matt-pen-keychain-set',
    name: 'MATT Pen + Keychain Executive Set',
    category_id: 'gift-sets',
    price: 450,
    mrp: 599,
    description: 'Corporate-grade matte black pen and matching round metal keychain encased in a velvet cushion gift case.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Midnight Matte Black']),
    packaging: 'Deluxe Presentation Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'zigzag-pen',
    name: 'ZigZag Pattern Textured Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 350,
    description: 'Unique geometric zigzag grip texture pen for effortless handwriting and sharp name personalization.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Glossy Jet Black', 'Gunmetal Grey']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'wooden-pen',
    name: 'Natural Bamboo Wooden Pen',
    category_id: 'pens-stationery',
    price: 199,
    mrp: 299,
    description: 'Eco-conscious handcrafted natural bamboo wood pen with laser burnt engraving of your name or inspirational quote.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Natural Maple', 'Dark Walnut']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'wooden-keychain',
    name: 'Handcrafted Wooden Keychain',
    category_id: 'keychains',
    price: 150,
    mrp: 220,
    description: 'Lightweight polished natural wood keychain engraved with names, initials, company logos, or dates.',
    customisation_options: JSON.stringify(['With Name Engraving', 'Logo Engraving']),
    variants: JSON.stringify(['Rectangle Rounded', 'Oval', 'Hexagon']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1614312015093-6c7b9c6f2c7d?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'blue-metal-pen-keychain-combo',
    name: 'Royal Blue Metal Pen & Keychain Combo',
    category_id: 'gift-sets',
    price: 250,
    mrp: 399,
    description: 'Dazzling royal blue lacquered metal pen and matching pill-shaped metal keychain with custom silver-finish laser etching.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Royal Blue Chrome']),
    packaging: 'Custom Molded Velvet Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'rush-matt-pen-keychain-combo',
    name: 'Rush Matt Metal Pen & Keychain Combo',
    category_id: 'gift-sets',
    price: 350,
    mrp: 499,
    description: 'Brushed metal finish with weighted pen body and round medallion keychain, designed for executive everyday carry.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Rush Matte Black']),
    packaging: 'Velvet Bed Gift Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'parker-copy-pen',
    name: 'Classic Parker Tribute Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 350,
    description: 'Iconic arrow clip design with glossy black resin barrel and gold trim. A timeless silhouette with personalized engraving.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Classic Gloss Black']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'black-zari-pen',
    name: 'Midnight Black Zari Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 350,
    description: 'Exquisite embossed black and gold zari pattern barrel. Heavyweight metal body with permanent name engraving.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Black Gold Filigree']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'square-diamond-pen',
    name: 'Square Diamond Cut Metal Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 350,
    description: 'Geometric diamond-faceted upper barrel with smooth lower grip. Available in high-gloss luxury colorways.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Rose Gold', 'Silver', 'Black', 'Gold']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'benz-metal-pen',
    name: 'Benz Sleek Metal Pen',
    category_id: 'pens-stationery',
    price: 199,
    mrp: 299,
    description: 'Aerodynamic curved pocket clip with metallic lacquered barrel. Smooth twist mechanism and clean laser lettering.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Metallic Blue', 'Ruby Red', 'Midnight Black', 'Silver']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'slim-cross-metal-pen',
    name: 'Slim Cross Silhouette Metal Pen',
    category_id: 'pens-stationery',
    price: 250,
    mrp: 350,
    description: 'Ultra-slender minimalist profile for planners and notebooks. Clean gold clip and sharp custom name typography.',
    customisation_options: JSON.stringify(['With Name Engraving']),
    variants: JSON.stringify(['Matte Black Gold', 'Full Chrome']),
    packaging: 'Paper Box Packing',
    add_ons: JSON.stringify([{ name: 'Acrylic Box', price: 20 }]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'doctor-pen-keychain-combo',
    name: 'Doctor (Dr.) Pen & Keychain Combo',
    category_id: 'gift-sets',
    price: 399,
    mrp: 550,
    description: 'Dedicated profession tribute set for Medical Doctors with the Caduceus medical emblem, engraved doctor name, and custom pen in gift box.',
    customisation_options: JSON.stringify(['Doctor Name Engraving', 'Caduceus / Stethoscope Emblem']),
    variants: JSON.stringify(['Doctor Professional Set']),
    packaging: 'With Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'ca-pen-keychain-combo',
    name: 'Chartered Accountant (CA) Combo Set',
    category_id: 'gift-sets',
    price: 399,
    mrp: 550,
    description: 'Official CA logo insignia keychain and matching custom engraved metallic pen for qualified and aspiring Chartered Accountants.',
    customisation_options: JSON.stringify(['CA Name Engraving', 'CA Logo']),
    variants: JSON.stringify(['CA Professional Set']),
    packaging: 'With Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'advocate-pen-keychain-combo',
    name: 'Advocate (Lawyer) Pen & Keychain Set',
    category_id: 'gift-sets',
    price: 399,
    mrp: 550,
    description: 'Scale of Justice emblem round keychain paired with a regal engraved black-gold pen. Perfect gift for advocates and law graduates.',
    customisation_options: JSON.stringify(['Advocate Name Engraving', 'Justice Scales Logo']),
    variants: JSON.stringify(['Advocate Professional Set']),
    packaging: 'With Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },

  // 3. Stainless Steel Keychains, Kadas & Pendant Bars
  {
    id: 'stainless-steel-ca-keychain',
    name: 'Stainless Steel Cutout CA Keychain',
    category_id: 'stainless-steel',
    price: 250,
    mrp: 350,
    description: 'Solid surgical-grade stainless steel cutout CA monogram with custom text bar beneath. Rust-proof and laser polished.',
    customisation_options: JSON.stringify(['With Single Side Engraving (Your Text Here)']),
    variants: JSON.stringify(['Silver Steel']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'stainless-steel-dr-keychain',
    name: 'Doctor (Dr.) Stainless Steel Keychain',
    category_id: 'stainless-steel',
    price: 250,
    mrp: 350,
    description: 'Caduceus medical staff shaped steel keychain with high-definition laser engraving on both front and back.',
    customisation_options: JSON.stringify(['With Both Side Engraving']),
    variants: JSON.stringify(['Mirror Polished Steel']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'stainless-steel-dentist-keychain',
    name: 'Dentist Tooth Shape Steel Keychain',
    category_id: 'stainless-steel',
    price: 250,
    mrp: 350,
    description: 'Charming tooth silhouette steel keychain personalized for dentists, dental clinics, and hygienists.',
    customisation_options: JSON.stringify(['With Both Side Engraving (Doctor Name + Clinic Tagline)']),
    variants: JSON.stringify(['Silver Finish']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'stainless-steel-advocate-keychain',
    name: 'Advocate Emblem Steel Keychain',
    category_id: 'stainless-steel',
    price: 250,
    mrp: 350,
    description: 'Circular stainless steel medallion with embossed Scales of Justice emblem and lower banner for advocate title.',
    customisation_options: JSON.stringify(['With Both Side Engraving']),
    variants: JSON.stringify(['Silver Polished']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'stainless-steel-calendar-keychain',
    name: 'Special Date Calendar & Heart Keychain',
    category_id: 'stainless-steel',
    price: 299,
    mrp: 450,
    description: 'Commemorate your anniversary or birthday with an engraved monthly calendar marking the exact date, plus an attached heart charm with initials.',
    customisation_options: JSON.stringify(['Month & Date Engraving', 'Heart Initials', 'Backside Custom Message']),
    variants: JSON.stringify(['Silver Mirror Steel']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'stainless-steel-bone-pet-keychain',
    name: 'Bone Shape Stainless Steel Pet Tag',
    category_id: 'stainless-steel',
    price: 250,
    mrp: 350,
    description: 'Cute dog bone shaped stainless steel tag for pets or keychains. Deep double-sided laser engraving with pet name & contact number.',
    customisation_options: JSON.stringify(['With Both Side Engraving']),
    variants: JSON.stringify(['Silver Steel']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'stainless-steel-i-love-you-keychain',
    name: 'I Love You Monogram Steel Keychain',
    category_id: 'stainless-steel',
    price: 250,
    mrp: 350,
    description: 'Bold cutout 3D typography keychain celebrating love. Personalized with names on the lower bar.',
    customisation_options: JSON.stringify(['With Single Side Engraving']),
    variants: JSON.stringify(['Silver Mirror Steel']),
    packaging: 'Standard Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'half-kada-8mm',
    name: 'Personalized Half Kada (8 mm)',
    category_id: 'stainless-steel',
    price: 399,
    mrp: 599,
    description: 'Premium open-cuff 8mm stainless steel kada bracelet with custom laser engraving of names, roman numerals, or coordinates.',
    customisation_options: JSON.stringify(['One Side Engraving (Outer or Inner)']),
    variants: JSON.stringify(['Black', 'Golden', 'Rosegold', 'Silver']),
    packaging: 'Poly Packing / Velvet Pouch',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'full-kada-6mm',
    name: 'Personalized Full Kada (6 mm)',
    category_id: 'stainless-steel',
    price: 450,
    mrp: 650,
    description: 'Solid round 6mm Kada bracelet with dual-sided personalized laser engraving. Tarnish-resistant surgical steel.',
    customisation_options: JSON.stringify(['Two Side Engraving (Front & Inner Secret Text)']),
    variants: JSON.stringify(['Black', 'Golden', 'Rosegold', 'Silver']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'secret-pendant-bar-2-names',
    name: 'Secret Pendant Bar (2 Names)',
    category_id: 'stainless-steel',
    price: 399,
    mrp: 599,
    description: 'Slender vertical 3D pillar pendant on a durable stainless chain. Personalized with 2 names on single side.',
    customisation_options: JSON.stringify(['2 Names Single Side Engraving']),
    variants: JSON.stringify(['Black', 'Golden', 'Rosegold', 'Silver']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'secret-pendant-bar-4-side',
    name: 'Secret 4-Sided Pillar Pendant Bar',
    category_id: 'stainless-steel',
    price: 399,
    mrp: 599,
    description: 'Four-sided vertical bar pendant where each face can carry a secret name, date, anniversary, coordinates, or symbols.',
    customisation_options: JSON.stringify(['4-Side Custom Engraving']),
    variants: JSON.stringify(['Black', 'Golden', 'Rosegold', 'Silver']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'bar-keychain-4-side',
    name: 'Solid 4-Sided Pillar Bar Keychain',
    category_id: 'stainless-steel',
    price: 399,
    mrp: 599,
    description: 'Heavyweight cuboid bar keychain with deep laser engraving on all 4 sides. Drive safe messages, names, and coordinates.',
    customisation_options: JSON.stringify(['4-Side Custom Engraving']),
    variants: JSON.stringify(['Black', 'Golden', 'Rosegold', 'Silver']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'metal-keychain-round',
    name: 'Round Classic Metal Keychain',
    category_id: 'keychains',
    price: 199,
    mrp: 299,
    description: 'Circular metallic disc keychain with dual-sided crisp laser engraving of names, quotes, vehicle numbers, or logos.',
    customisation_options: JSON.stringify(['Both Side Engraving']),
    variants: JSON.stringify(['Gunmetal Chrome', 'Silver']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1614312015093-6c7b9c6f2c7d?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'metal-keychain-rectangle',
    name: 'Rectangle Metal Tag Keychain',
    category_id: 'keychains',
    price: 199,
    mrp: 299,
    description: 'Sleek beveled rectangle tag keychain with lustrous border and dual-sided custom text engraving.',
    customisation_options: JSON.stringify(['Both Side Engraving']),
    variants: JSON.stringify(['Gunmetal Chrome', 'Silver']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1614312015093-6c7b9c6f2c7d?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },

  // 4. Leather Products
  {
    id: 'faux-leather-keychain',
    name: 'Bespoke Faux Leather Keychain',
    category_id: 'leather-gifts',
    price: 199,
    mrp: 299,
    description: 'Artisanal faux leather loop keychain fitted with a metallic charm and embossed name tag strip.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Tan', 'Green', 'Brown', 'Blue']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-passport-cover',
    name: 'Custom Faux Leather Passport Cover',
    category_id: 'leather-gifts',
    price: 299,
    mrp: 450,
    description: 'Keep your passport safe in style. High-grade faux leather with metal aviation/travel charm and personalized name strip.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Tan', 'Green', 'Brown', 'Blue']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'premium-pu-passport-cover',
    name: 'Premium PU Pastel Passport Cover',
    category_id: 'leather-gifts',
    price: 350,
    mrp: 499,
    description: 'Minimalist pastel PU leather passport cover with direct hot-stamp / laser engraved typography and artwork.',
    customisation_options: JSON.stringify(['Direct Name & Quote Engraving']),
    variants: JSON.stringify(['White', 'Baby Pink', 'Light Blue']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-card-holder',
    name: 'Faux Leather Minimalist Card Holder',
    category_id: 'leather-gifts',
    price: 250,
    mrp: 350,
    description: 'Compact slim pocket wallet with multiple credit card slots and central cash sleeve, personalized with a charm and name strip.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Tan', 'Green', 'Brown', 'Blue']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-mens-wallet',
    name: "Faux Leather Men's Bi-fold Wallet",
    category_id: 'leather-gifts',
    price: 299,
    mrp: 450,
    description: "Classic men's bi-fold wallet featuring currency slots, coin pouch, and card slots, personalized with signature charm and name strip.",
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Tan', 'Green', 'Brown', 'Blue']),
    packaging: 'Standard Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-mens-wallet-full-zip',
    name: "Faux Leather Men's Wallet (Full Zip)",
    category_id: 'leather-gifts',
    price: 350,
    mrp: 499,
    description: 'Secure full-zipper circumference wallet protecting cash and cards, adorned with your choice of charm and name tag.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Tan', 'Green', 'Brown', 'Blue']),
    packaging: 'Standard Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'premium-leather-mens-wallet',
    name: "Premium Leather Men's Wallet",
    category_id: 'leather-gifts',
    price: 399,
    mrp: 599,
    description: 'Super-soft textured premium grade leather with contrast edge stitching and metal emblem charm + name personalization.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Tan', 'Green', 'Brown', 'Blue']),
    packaging: 'Gift Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'wallet-gold-zari-pen-set',
    name: "Men's Wallet + Gold Zari Pen Set",
    category_id: 'gift-sets',
    price: 499,
    mrp: 699,
    description: "An impressive gift set combining a personalized Men's Wallet (Charm + Name Strip) with a Gold Zari Pen (Name Engraved).",
    customisation_options: JSON.stringify(['Wallet: 1 Charm + 1 Strip with Name', 'Pen: With Name Engraved']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Deluxe Gift Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'wallet-pen-keychain-set',
    name: "Men's Wallet + Pen + Metal Keychain Trio",
    category_id: 'gift-sets',
    price: 599,
    mrp: 799,
    description: "3-piece executive suite: Custom Men's Wallet, laser-engraved metal pen, and double-sided engraved metal keychain in a velvet gift box.",
    customisation_options: JSON.stringify(['Wallet: Charm + Name Strip', 'Pen: Name Engraved', 'Keychain: Both Side Engraving']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Deluxe 3-in-1 Presentation Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'wallet-keychain-duo-set',
    name: "Men's Wallet + Leather Keychain Set",
    category_id: 'gift-sets',
    price: 499,
    mrp: 650,
    description: "Matching leather pair: Custom Men's Wallet with charm & name strip alongside a coordinated leather keychain in a gift box.",
    customisation_options: JSON.stringify(['Wallet: 1 Charm + 1 Strip', 'Keychain: 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Presentation Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'mens-combo-set-of-3',
    name: "Men's Bespoke Combo Set of 3",
    category_id: 'gift-sets',
    price: 699,
    mrp: 999,
    description: "Coordinated luxury ensemble: Men's Wallet + Leather Keychain + Sunglasses Hard Case, all personalized with matching charms and name strips.",
    customisation_options: JSON.stringify(['Wallet (Charm + Strip)', 'Keychain (Strip)', 'Sunglass Cover (Charm + Strip)']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green', 'Olive', 'Wine']),
    packaging: 'Signature Gift Hamper Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'mens-combo-set-of-4-faux',
    name: "Men's Bespoke Combo Set of 4 (Faux Leather)",
    category_id: 'gift-sets',
    price: 899,
    mrp: 1299,
    description: "Ultimate gentleman's hamper: Men's Wallet, Keychain, Sunglasses Case, and Passport Cover in a luxury presentation box.",
    customisation_options: JSON.stringify(['Wallet (Charm + Strip)', 'Keychain (Strip)', 'Sunglass Cover (Charm + Strip)', 'Passport Cover (Charm + Strip)']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Luxury 4-Piece Hamper Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'mens-combo-set-of-4-premium',
    name: "Men's Bespoke Combo Set of 4 (Premium Leather)",
    category_id: 'gift-sets',
    price: 899,
    mrp: 1399,
    description: "Ultra-premium textured leather hamper with Wallet, Keychain, Sunglasses Case, and Passport Cover.",
    customisation_options: JSON.stringify(['Wallet (Charm + Strip)', 'Keychain (Strip)', 'Sunglass Cover (Charm + Strip)', 'Passport Cover (Charm + Strip)']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Luxury 4-Piece Hamper Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-sunglass-case',
    name: 'Custom Sunglasses Case / Cover',
    category_id: 'leather-gifts',
    price: 299,
    mrp: 450,
    description: 'Structured hard-case eyewear cover wrapped in soft leather with secure button closure, charm, and personalized name strip.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green', 'Navy Blue', 'Olive']),
    packaging: 'Standard Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-ladies-purse',
    name: "Bespoke Ladies Purse / Clutch",
    category_id: 'leather-gifts',
    price: 350,
    mrp: 499,
    description: 'Elegant bi-fold ladies wallet clutch with phone compartment and card sleeves, embellished with a charm and name strip.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Standard Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'faux-leather-ladies-purse-pati-zip',
    name: 'Ladies Purse with Pati & Zip Pouch',
    category_id: 'leather-gifts',
    price: 499,
    mrp: 699,
    description: 'Spacious tri-fold envelope clutch with metal button flap, internal zippered cash pouch, multiple card slots, charm, and name strip.',
    customisation_options: JSON.stringify(['1 Charm + 1 Strip with Name']),
    variants: JSON.stringify(['Black', 'Blue', 'Tan', 'Brown', 'Green']),
    packaging: 'Gift Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },

  // 5. Engraving Bottles / Mugs / Organizers
  {
    id: 'desktop-organiser-01',
    name: 'Executive Desktop Organiser 01',
    category_id: 'diaries',
    price: 650,
    mrp: 899,
    description: 'Multi-functional wooden & leather desktop organizer with pen holder, perpetual calendar blocks, clock slot, and laser-engraved corporate logo / name.',
    customisation_options: JSON.stringify(['With Name Engraving / Logo Engraving']),
    variants: JSON.stringify(['Walnut & Matte Black']),
    packaging: 'Heavy Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'temperature-bottle-500ml',
    name: 'Smart LED Temperature Bottle (500ml)',
    category_id: 'bottles-mugs',
    price: 399,
    mrp: 599,
    description: 'Double-wall stainless steel vacuum insulated flask with smart LED touch-screen digital temperature indicator cap. Engraved with your name or logo.',
    customisation_options: JSON.stringify(['With Name Engraving / Logo Engraving (Send design)']),
    variants: JSON.stringify(['Matte Black (500ml)']),
    packaging: 'Individual Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'vacuum-flask-set-3-cups',
    name: 'Stainless Steel Vacuum Flask + 3 Cups Gift Set',
    category_id: 'bottles-mugs',
    price: 599,
    mrp: 899,
    description: '500ml double-walled thermal flask for hot/cold beverages accompanied by 3 matching insulated stainless steel serving cups. Name/logo engraved.',
    customisation_options: JSON.stringify(['With Name Engraving / Corporate Logo']),
    variants: JSON.stringify(['Matte Black Set (500ml)']),
    packaging: 'Luxury Gift Hamper Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },

  // 6. Leather Diaries
  {
    id: 'diary-pen-set-a6-dggsa6br',
    name: 'A6 Leather Diary + Pen Gift Set (DGGSA6BR)',
    category_id: 'diaries',
    price: 499,
    mrp: 699,
    description: 'Compact A6 executive brown leather notebook with magnetic buckle strap and coordinated engraved metal pen in a presentation box.',
    customisation_options: JSON.stringify(['With Name Engraving / Logo Engraving']),
    variants: JSON.stringify(['Cognac Brown A6']),
    packaging: 'Premium Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'executive-diary-a5-dgd36',
    name: 'Executive A5 Leather Diary (DGD36)',
    category_id: 'diaries',
    price: 450,
    mrp: 650,
    description: 'A5 size, 116 high-GSM cream ruled pages, integrated 4-year calendar reference, ribbon bookmark, and custom logo/name engraving on front cover plate.',
    customisation_options: JSON.stringify(['With Name Engraving / Logo Engraving']),
    variants: JSON.stringify(['Tan Brown A5 (116 Pages)']),
    packaging: 'Protective Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'premium-diary-a5-dgd40',
    name: 'Premium A5 Leather Diary (DGD40)',
    category_id: 'diaries',
    price: 650,
    mrp: 899,
    description: 'Rich dark espresso leatherette cover with metal monogram emblem, 116 archival pages, 4-year calendar, and pen loop.',
    customisation_options: JSON.stringify(['With Name Engraving / Logo Engraving']),
    variants: JSON.stringify(['Espresso Brown A5 (116 Pages)']),
    packaging: 'Presentation Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'diary-pen-set-a5-dggsa5br',
    name: 'A5 Leather Diary + Pen Gift Set (DGGSA5BR)',
    category_id: 'diaries',
    price: 599,
    mrp: 799,
    description: 'Full A5 executive brown leather diary paired with an engraved metal pen in a deluxe foam-lined gift box.',
    customisation_options: JSON.stringify(['With Name Engraving / Logo Engraving']),
    variants: JSON.stringify(['Classic Brown A5']),
    packaging: 'Premium Box Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },

  // 7. Sublimation Products & Lifestyle
  {
    id: 'fridge-magnet-square-35',
    name: 'Square Photo Fridge Magnet (3.5 Inch)',
    category_id: 'home-lifestyle',
    price: 199,
    mrp: 299,
    description: 'High-gloss acrylic photo fridge magnet with edge-to-edge sublimation printing for your favorite memories.',
    customisation_options: JSON.stringify(['With Photo Printing / Design']),
    variants: JSON.stringify(['Square 3.5 x 3.5 Inch']),
    packaging: 'Individual Poly Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'fridge-magnet-round-35',
    name: 'Round Photo Fridge Magnet (3.5 Inch)',
    category_id: 'home-lifestyle',
    price: 199,
    mrp: 299,
    description: 'Circular photo magnet with vibrant color fidelity and durable magnetic backing.',
    customisation_options: JSON.stringify(['With Photo Printing / Design']),
    variants: JSON.stringify(['Round 3.5 Inch Diameter']),
    packaging: 'Individual Poly Packaging',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'polyester-tshirt-printed-130gsm',
    name: 'Custom Printed Polyester T-Shirt (130 GSM)',
    category_id: 'apparel',
    price: 299,
    mrp: 450,
    description: 'Lightweight, breathable 130 GSM polyester tee with full A4-size vivid sublimation photo or graphic print.',
    customisation_options: JSON.stringify(['With A4 Size Printing (Photo / Text / Logo)']),
    variants: JSON.stringify(['Size 18', 'Size 20', 'Size 22', 'S', 'M', 'L', 'XL', 'XXL']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'polyester-tshirt-plain-130gsm',
    name: 'Plain Polyester T-Shirt (130 GSM)',
    category_id: 'apparel',
    price: 199,
    mrp: 299,
    description: 'Clean solid polyester t-shirt ideal for everyday activewear, promotional campaigns, or DIY crafts.',
    customisation_options: JSON.stringify(['Plain']),
    variants: JSON.stringify(['Size 18 to XXL', 'White', 'Black', 'Grey', 'Navy', 'Maroon']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'metal-badge-44mm',
    name: 'Custom Printed Metal Pin Badge (44 mm)',
    category_id: 'home-lifestyle',
    price: 40,
    mrp: 60,
    description: 'High-gloss 44mm pin-back button badge with water-resistant coating. Great for events, campaigns, clubs, and parties.',
    customisation_options: JSON.stringify(['Custom Badge Artwork / Photo Print']),
    variants: JSON.stringify(['Size 1 (44 mm)']),
    packaging: 'Bulk Pack / Individual Poly',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'metal-badge-58mm',
    name: 'Custom Printed Metal Pin Badge (58 mm)',
    category_id: 'home-lifestyle',
    price: 50,
    mrp: 75,
    description: 'Larger 58mm metal pin badge for maximum visual impact with photo and text printing.',
    customisation_options: JSON.stringify(['Custom Badge Artwork / Photo Print']),
    variants: JSON.stringify(['Size 2 (58 mm)']),
    packaging: 'Bulk Pack / Individual Poly',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'polycotton-tshirt-180gsm',
    name: 'Premium PolyCotton T-Shirt (170-180 GSM)',
    category_id: 'apparel',
    price: 350,
    mrp: 499,
    description: 'Comfortable cotton-feel blend with durable shape retention and vibrant A4 front/back custom printing.',
    customisation_options: JSON.stringify(['With A4 Size printing']),
    variants: JSON.stringify(['Size 18', 'Size 20', 'S', 'M', 'L', 'XL', 'XXL']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'dryfit-collar-tshirt-180gsm',
    name: 'Printed Dryfit Polo T-Shirt with Collar (180 GSM)',
    category_id: 'apparel',
    price: 399,
    mrp: 599,
    description: 'Sporty corporate polo shirt with ribbed collar and button placket. Moisture-wicking dryfit fabric customized with chest or back prints.',
    customisation_options: JSON.stringify(['With A4 Size printing / Chest Logo']),
    variants: JSON.stringify(['Size S', 'Size M', 'Size L', 'Size XL', 'Size XXL']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'oversize-cotton-tshirt-200gsm',
    name: 'Oversize Streetwear Cotton T-Shirt (200 GSM)',
    category_id: 'apparel',
    price: 499,
    mrp: 799,
    description: 'Heavyweight 200 GSM 100% bio-washed drop-shoulder streetwear oversized tee with HD A4 back or chest graphic print.',
    customisation_options: JSON.stringify(['With A4 Size Print']),
    variants: JSON.stringify(['Light Pink', 'Red', 'Lavender', 'White', 'Black', 'Sizes S/M/L/XL/XXL']),
    packaging: 'Zip Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'cotton-hoodie-320gsm',
    name: 'Heavyweight Cotton Hoodie (320 GSM)',
    category_id: 'apparel',
    price: 650,
    mrp: 999,
    description: 'Ultra-warm 320 GSM fleece-lined cotton hoodie with kangaroo pocket, double-layered hood, and custom A4 print.',
    customisation_options: JSON.stringify(['With A4 Size print']),
    variants: JSON.stringify(['Black (Sizes S / M / L / XL / XXL)']),
    packaging: 'Premium Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'sweat-shirt-320gsm',
    name: 'Crewneck Sweatshirt (320 GSM)',
    category_id: 'apparel',
    price: 599,
    mrp: 899,
    description: 'Soft brushed fleece 320 GSM crewneck pullover with ribbed cuffs and hem. Customized with A4 graphics or quotes.',
    customisation_options: JSON.stringify(['With A4 Size Print']),
    variants: JSON.stringify(['Black (Sizes S / M / L / XL / XXL)']),
    packaging: 'Premium Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'printed-baby-rompers-red',
    name: 'Custom Printed Baby Romper (Red Trim)',
    category_id: 'apparel',
    price: 299,
    mrp: 450,
    description: 'Soft hypoallergenic cotton baby onesie romper with snap buttons and adorable personalized quotes/names.',
    customisation_options: JSON.stringify(['With A4 Size printing (e.g. "Nani ke ghar jaungi...")']),
    variants: JSON.stringify(['Red Trim (Free Size 0-12M)']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'printed-baby-rompers-blue',
    name: 'Custom Printed Baby Romper (Blue Trim)',
    category_id: 'apparel',
    price: 299,
    mrp: 450,
    description: 'Cute baby bodysuit romper with blue contrast trim and custom cute baby text or illustrations.',
    customisation_options: JSON.stringify(['With A4 Size printing (e.g. "Maamu ki Jaan...")']),
    variants: JSON.stringify(['Blue Trim (Free Size 0-12M)']),
    packaging: 'Poly Packing',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'printed-mouse-pad-3mm',
    name: 'Personalized Gaming Mouse Pad (3 mm)',
    category_id: 'home-lifestyle',
    price: 150,
    mrp: 250,
    description: 'Smooth microfiber cloth surface with non-slip natural rubber base and vibrant edge-to-edge photo/graphic printing.',
    customisation_options: JSON.stringify(['With A4 Size printing (Any Photo / Artwork)']),
    variants: JSON.stringify(['3 mm Thickness Standard Size']),
    packaging: 'Protective Sleeve',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'red-fur-pillow-square-16x16',
    name: 'Red Velvet Fur Square Pillow (16x16 Inch)',
    category_id: 'home-lifestyle',
    price: 599,
    mrp: 850,
    description: 'Luxuriously soft red faux-fur border square cushion with central white sequin/satin patch printed with your photo.',
    customisation_options: JSON.stringify(['Any photo print']),
    variants: JSON.stringify(['Red Fur Square (16x16 inch)']),
    packaging: 'Compressed Packaging with Filler Included',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'square-pillow-white-16x16',
    name: 'Satin White Square Photo Cushion (16x16 Inch)',
    category_id: 'home-lifestyle',
    price: 499,
    mrp: 699,
    description: 'Silky smooth white satin cushion with vibrant edge-to-edge photo collage or couple portrait printing. Filler included.',
    customisation_options: JSON.stringify(['Any photo']),
    variants: JSON.stringify(['White Satin Square (16x16 inch)']),
    packaging: 'Individual Packaging with Cushion Insert',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 0,
    is_featured: 0,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'ceramic-mug-white',
    name: 'Custom White Ceramic Coffee Mug',
    category_id: 'bottles-mugs',
    price: 250,
    mrp: 350,
    description: '325ml premium ceramic coffee mug with durable glossy glaze. Personalized with Spotify code song barcodes, photos, names, or quotes.',
    customisation_options: JSON.stringify(['Any photo / name / logo / Spotify code']),
    variants: JSON.stringify(['Glossy White (325ml)']),
    packaging: 'Smash-proof Thermocol Box',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
  {
    id: 'red-fur-pillow-heart-16x16',
    name: 'Romantic Heart-Shaped Red Fur Pillow (16x16 Inch)',
    category_id: 'home-lifestyle',
    price: 599,
    mrp: 850,
    description: 'Heart-shaped romantic plush red fur cushion with high-definition photo print center. The most loved gift for anniversaries and birthdays.',
    customisation_options: JSON.stringify(['Any photo print']),
    variants: JSON.stringify(['Heart Shape (16x16 inch)']),
    packaging: 'Gift Packaging with Soft Filler',
    add_ons: JSON.stringify([]),
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80',
    ]),
    is_bestseller: 1,
    is_featured: 1,
    is_in_stock: 1,
    bulk_available: 1,
  },
];

export const defaultSettings = [
  { key: 'whatsapp_number', value: '919730672323' },
  { key: 'instagram_handle', value: 'mad-bespoke' },
  { key: 'contact_email', value: 'orders@madbespoke.in' },
  { key: 'contact_phone', value: '+91 9730672323' },
  { key: 'contact_location', value: 'Mumbai & Pan India Delivery' },
  { key: 'banner_announcement', value: '✨ Free Custom Engraving on all orders this week! Dispatched within 24-48 hours.' },
  { key: 'currency_symbol', value: '₹' },
];

export async function seedDatabase() {
  console.log('[Turso DB Seeder] Starting database seed...');
  await initSchema();

  // Clear existing items for fresh seed
  await db.execute('DELETE FROM categories');
  await db.execute('DELETE FROM products');
  await db.execute('DELETE FROM settings');

  // Insert categories
  for (const cat of categoriesData) {
    await db.execute({
      sql: `INSERT INTO categories (id, name, icon, description, display_order, image_url) VALUES (?, ?, ?, ?, ?, ?)`,
      args: [cat.id, cat.name, cat.icon, cat.description, cat.display_order, cat.image_url],
    });
  }
  console.log(`[Turso DB Seeder] Seeded ${categoriesData.length} categories.`);

  // Insert products
  for (const prod of productsData) {
    await db.execute({
      sql: `INSERT INTO products (id, name, category_id, price, mrp, description, customisation_options, variants, packaging, add_ons, images, is_bestseller, is_featured, is_in_stock, bulk_available)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        prod.id,
        prod.name,
        prod.category_id,
        prod.price,
        prod.mrp,
        prod.description,
        prod.customisation_options,
        prod.variants,
        prod.packaging,
        prod.add_ons,
        prod.images,
        prod.is_bestseller,
        prod.is_featured,
        prod.is_in_stock,
        prod.bulk_available,
      ],
    });
  }
  console.log(`[Turso DB Seeder] Seeded ${productsData.length} catalog products.`);

  // Insert settings
  for (const setting of defaultSettings) {
    await db.execute({
      sql: `INSERT INTO settings (key, value) VALUES (?, ?)`,
      args: [setting.key, setting.value],
    });
  }
  console.log(`[Turso DB Seeder] Seeded default settings.`);

  console.log('[Turso DB Seeder] Seeding finished successfully!');
}

// Run if called directly
if (process.argv[1]?.endsWith('seeder.js')) {
  seedDatabase()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Seeder failed:', err);
      process.exit(1);
    });
}
